### ISSUE TITLE
Enable tests to run on UI thread

### ISSUE THREAD

**Issue by onovotny** [xunit/devices.xunit#18]
The UI thread plays an important role in device apps. Certain tests might need to execute on it.

The STAExample can likely be adapted:
https://github.com/xunit/samples.xunit/tree/master/STAExamples

**Comment by bradwilson** [comment]
Related: https://github.com/xunit/samples.xunit/pull/12

**Comment by onovotny** [comment]
Will be in 1.2-rc4
