### ISSUE TITLE
If any of test assemblies has no tests - other assemblies don't get tests loaded as well

### ISSUE THREAD

**Issue by Ivan-Razhnou** [xunit/devices.xunit#19]
I've created very simple skeleton of solution with PCL unit test library & iOS unit test library as suggested in your How To. I uncommented line for PCL in AppDelegate and added few tests in PCL library - as result nothing was discovered by runner.

I think that once runner get test assembly loaded and test assembly has no tests - all further test assemblies are ignored

**Comment by onovotny** [comment]
Do you have a repro project somewhere?

**Comment by onovotny** [comment]
Closing as I cannot repro with 1.2-rc3. If you see this again, please re-open or let me know.
