### ISSUE TITLE
Automating Windows Phone (silverlight based) unit tests

### ISSUE THREAD

**Issue by darind** [xunit/devices.xunit#20]
Silverlight based Windows Phone unit tests cannot be easily automated with the `vstest.console.exe` runner because the target project in which they are hosted is a standard Windows Phone application contrary to the built-in MSTest Windows Phone (Silverlight) Unit Test project. Is this scenario supported?

**Comment by onovotny** [comment]
Hi,

I'm not sure what you're asking here? I believe the vstest mechanism uses the same test adapters as the Visual Studio Test Explorer. Due to the way it's implemented on the VS side, it's impossible to create 3rd party adapters for WP8 Silverlight.
