### ISSUE TITLE
Installing 1.2.0-rc1 in VS2013

### ISSUE THREAD

**Issue by rdavisau** [xunit/devices.xunit#21]
Hi, 

Thanks for this project! I found that I couldn't install the latest RC with WP8.1 support into my solution when running VS2013. I get `Install-Package : 'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.`

 ![](http://imgur.com/rHOJAYg.png)

In VS2015 I had no trouble, I wonder if it is related the to change in NuGet dependency version resolution?

**Comment by bradwilson** [comment]
Make sure you're running the latest NuGet package manager inside of Visual Studio. For 2013, that should be `2.8.60318.734`.

**Comment by rdavisau** [comment]
Ah - rookie error! AOK after updating, thanks.
