### ISSUE TITLE
Filtered tests never have status updated on Android

### ISSUE THREAD

**Issue by kentcb** [xunit/devices.xunit#22]
When running a test under Android when a filter has been entered, the status for the test is never updated. It just kind of hangs indefinitely. Running the same test without a filter (or on iOS with or without a filter) works as expected.

A repro solution can be downloaded from [here](http://cl.ly/3q3K3q2C3y1F).

Here's an example showing the repro with a filter entered and the test consequently stuck:

![nexus 5 lollipop screenshot 1](https://cloud.githubusercontent.com/assets/1901832/9778365/82003b46-57ae-11e5-9d8d-71585ce160e6.png)

**Comment by onovotny** [comment]
I just tried this in VS using the VS Android emulator and could not repro. I'm using a 5.1.1 android image.

![repro](https://cloud.githubusercontent.com/assets/1427284/9799067/ef255ca0-57d2-11e5-8272-a5d965d7d38c.png)

**Comment by kentcb** [comment]
This fails for me on both device and emulator (Nexus 5 lollipop).

I'm using XS stable channel. Are you on stable?

**Comment by onovotny** [comment]
I'm on stable, but I don't use XS. I'm using VS 2015 with the latest Xamarin tools...

**Comment by kentcb** [comment]
Actually, the problem is more subtle than I first realized. Here is what I can do to repro:

* run the xUnitTest.Droid project on either device or emulator
* tap the xUnitTest project in the test runner
* tap the filter entry
* enter "repro" or whatever
* tap the repro test

At this point, the test cell turns orange and stays that way indefinitely. However, I've just found that I can then tap *away* from the cell. It then updates its status but remains orange.

**Comment by onovotny** [comment]
Could this be a Xamarin Forms bug? There's really little that xUnit is doing other than running a test on tap of a test and/or the run filtered/all buttons. Everything else is Xam Forms databinding?

**Comment by kentcb** [comment]
Feels like it could be anything in the stack at this point :(

Thing is, it works in iOS. So perhaps it does have something to do with the droid platform implementation. But then why does it work for you via VS?

I'm currently updating my VS install to try it there (though it's on alpha).

**Comment by kentcb** [comment]
Ugh, after all those downloads and updates, I'm just getting deployment errors on my VS box. I give up.

This is not as big a deal as I originally thought because it is a UI quirk rather than a hang. I might get time to look into this further later on, but right now I need to move onto other things.

Thanks @onovotny

**Comment by onovotny** [comment]
I'll leave this issue open for awhile; if you get time to locate root cause, I'd be happy to look deeper.

**Comment by onovotny** [comment]
Has this still happened or can I close this issue?

**Comment by kentcb** [comment]
Sorry, meant to reply to this earlier but forgot. Yes, it's still an issue. tbh, I don't run tests in the devices runner often anymore, so this doesn't crop up as much. And when it does, I know exactly why the UI isn't updating and just tap around a bit so it does. But it would still be good to fix this at some point.

**Comment by onovotny** [comment]
I would like to fix this...but still not sure how to repro?

**Comment by onovotny** [comment]
Is this still an issue? Maybe a later Xam Forms fixed something? Can you please try 2.2-rc1 and let me know?

**Comment by kentcb** [comment]
Just tried this. It is indeed working now in 2.2-rc1 🎉 No doubt one of many XF bugs fixed since 2.0.1.
