### ISSUE TITLE
Test counts sometimes skipped on iOS

### ISSUE THREAD

**Issue by kentcb** [xunit/devices.xunit#24]
When running tests under iOS, sometimes the test count does not reflect the actual number of tests executed. For example, when running a single test multiple times, one can see output like this:

```
Tests run: 1 Passed: 1 Failed: 0 Skipped: 0
Tests run: 1 Passed: 1 Failed: 0 Skipped: 0
Tests run: 0 Passed: 0 Failed: 0 Skipped: 0
Tests run: 1 Passed: 1 Failed: 0 Skipped: 0
```

**Comment by onovotny** [comment]
Is this with 1.0 or 1.2-rc3? Can you please test/verify on 1.2-rc3 as there were many fixes there.

I fixed the count issue #23 was fixed for all platforms post-rc3.

**Comment by kentcb** [comment]
Just tried with 1.2-rc3 and get the same problem.

**Comment by onovotny** [comment]
yeah, that wouldn't be in rc3 as I just checked in a fix. It should be in the latest CI build though.

**Comment by onovotny** [comment]
Closing now, please let me know if you're still seeing this in the next RC or in the current CI builds.
