### ISSUE TITLE
Add "running" status

### ISSUE THREAD

**Issue by kentcb** [xunit/devices.xunit#27]
It would be cool if there was a "running" status so that one could quickly filter to those tests that are stuck in their execution (quite a common occurrence when writing async tests).

**Comment by onovotny** [comment]
Closing this out in favor or "long test detection". This is now in 2.2, but it's off by default.

You have to add an `xunit.runner.json` and enable the settings.

For Android it goes in the assets folder:
https://github.com/xunit/devices.xunit/blob/master/test/test.xunit.runner.android/Assets/xunit.runner.json
https://github.com/xunit/devices.xunit/blob/master/test/test.xunit.runner.android/test.xunit.runner.android.csproj#L75

and for iOS it's in the root 
https://github.com/xunit/devices.xunit/blob/master/test/test.xunit.runner.ios/xunit.runner.json
https://github.com/xunit/devices.xunit/blob/master/test/test.xunit.runner.ios/test.xunit.runner.ios.csproj#L154-L156
