### ISSUE TITLE
Breakpoints have stopped working in visual studio since last xamarin update.

### ISSUE THREAD

**Issue by kensykora** [xunit/devices.xunit#29]
I'm using xunit pretty extensively, this project is particularly great for running tests on the devices. However, after yesterday's major update, my breakpoints within unit tests are no longer causing the debugger to stop in visual studio. However, breakpoints do hit, but application execution is suspended -- it's just visual studio doesn't pick up on the breakpoint and I can't resume or step over, or anything like that.

Looking for ideas on how to troubleshoot this. Let me know if this belongs more in the xamarin territory. I figured I'd try here, because breakpoints still work within my application -- just not the test runner.

Visual Studio 2013

**Comment by kensykora** [comment]
Attached is a link with a minimum set of reproducible code and Xamarin version numbers of the platform I'm currently running on.

https://www.dropbox.com/sh/au84myj9dgmj8hw/AAC5Sd31ruAHtnbYyoSdE9yua?dl=0#

**Comment by onovotny** [comment]
I'm pretty sure this is a Xamarin issue/bug. I'd suggest opening up an issue there; feel free to cc me there.

**Comment by kensykora** [comment]
Agreed -- I sent an email to their support. If you want to shoot me an email with your email address, I'll copy you on the support chain.

**Comment by onovotny** [comment]
first at last dot org

**Comment by AArnott** [comment]
+1
I've subscribed to this thread, but please CC me as well.

**Comment by onovotny** [comment]
The Xamarin Bugzilla for this is here: https://bugzilla.xamarin.com/show_bug.cgi?id=36087

**Comment by jamesmontemagno** [comment]
Have you attempted to uninstall all of the Mono/Xamarin.Android runtimes from your device/emulator? sometimes that stuff can muck it up. Usually going through you installed apps on your android device and uninstalling them all then letting the latest can fix it up.

**Comment by kensykora** [comment]
It is an issue both in iOS and Android, so it's not just limited to Android.

**Comment by kentcb** [comment]
I reported this to Xamarin directly and they confirmed it was a bug. However, I only observed it in Android, not iOS. Ticket: https://bugzilla.xamarin.com/show_bug.cgi?id=36078

**Comment by kentcb** [comment]
@jamesmontemagno also, not really convinced this will help for two reasons:

1. Breakpoints work outside of tests (even in the startup activity for the test harness, just not the tests themselves)
2. Xam support were able to repro the issue

That said, I'll try your suggestion and report back here.

**Comment by digital-synapse** [comment]
Does anyone have any updates on this? Having the same problem. 
This makes TDD for xamarin/android next to impossible.

**Comment by bradwilson** [comment]
Shouldn't this bug be opened with Xamarin?

**Comment by onovotny** [comment]
There is an open bug, linked above. No progress on it so far other then their confirmation of a repro.

**Comment by kensykora** [comment]
For those here, I've been able to sometimes work around this issue if I put a breakpoint in the main thread that gets hit before breakpoints that happen within async/await code. If a breakpoint in the main thread hits, it seems to allow breakpoints in async code to hit also.

**Comment by AArnott** [comment]
For me, the app just hangs whenever it encounters a method with a breakpoint in it, including AppDelegate itself.

**Comment by onovotny** [comment]
I just sent them a support email via the priority queue....lets see what happens.

**Comment by kentcb** [comment]
@onovotny been there, done that. But please don't let that stop you. The more people shouting, the more likely this will be fixed.

I have found the most effective way of testing Xamarin applications is to.....not use Xamarin. I unload all Xamarin projects, put my tests in a PCL that I run via NCrunch or VS Test Runner, and do as much work as I can (services, view models) _without_ loading the Xamarin tool chain. Only once I'm done there do I reload the Xamarin projects, double-check tests pass in the devices, and wire up the views.

It's sad, but that's the sorry state of Xamarin's tool chain at the moment.

**Comment by digital-synapse** [comment]
@onovotny I hope they can get this patched for you before Xamarin Evolve 16 or its going to be pretty hard to do any kind of walkthough...

**Comment by onovotny** [comment]
Anyone want to give this a shot to confirm?
https://bugzilla.xamarin.com/show_bug.cgi?id=36078

https://www.dropbox.com/s/ugaodugklwkjboo/Xamarin.VisualStudio_4.0.1.102.msi?dl=0

There appears to be a fix.

**Comment by digital-synapse** [comment]
Sweet! I did some preliminary tests. This does appear to fix the async code breakpoints! Thank you this is very helpful!

**Comment by onovotny** [comment]
Closing as this should be fixed in the stable channel.
