### ISSUE TITLE
Show output from ITestOutputHelper

### ISSUE THREAD

**Issue by AArnott** [xunit/devices.xunit#31]
My tests log to `ITestOutputHelper` but the text from these logs doesn't appear to be accessible in the mobile test runner either for failed or successful tests.

**Comment by onovotny** [comment]
The devices runner currently does nothing with this. Question for you: where would you expect to see the output? Would a button to the left of the test result work? I assume that not all tests use this mechanism?

**Comment by AArnott** [comment]
`ITestOutputHelper` is the only supported xunit logging mechanism AFAIK. Not all tests log messages, but those that log should use it.

I expected to find the log output above the failure details after tapping a failed test. Or after tapping a successful test. Since I get details on a failed test by tapping, I'd hope to get all the details whether it passed or failed.

**Comment by onovotny** [comment]
I just checked in an update that should display this but I don't have any tests that currently use it...so I can't easily verify it.

Can you try out `1.2.3-build0004` from the CI feed? 
https://www.myget.org/F/xunit-xamarin/api/v2

**Comment by AArnott** [comment]
Your updated UX sounds good. I'll check it out later today and report back. Thanks. :)

**Comment by AArnott** [comment]
Confirmed on 1.2.3-build0010
