### ISSUE TITLE
Is this still accurate in the readme?

### ISSUE THREAD

**Issue by robertbaker** [xunit/devices.xunit#32]
`Basic functionality works -- tests are discoverable and runnable. There is a lot of room for improvements in each of the runner apps`

**Comment by onovotny** [comment]
I suppose so, it's worded vaguely intentionally ;)

That said, xUnit does fully work with all of its extensibility mechanisms supported. The runner still does have room for improvement.
  - Getting data back from runner to listening agent (remote)
  - trait display/filters
  - UI polish 
  - anything else that people request/want/etc.
