### ISSUE TITLE
In an android test app, how can I get the results of the test into TeamCity

### ISSUE THREAD

**Issue by robertbaker** [xunit/devices.xunit#40]

**Comment by onovotny** [comment]
I'm not aware of any way to do a CI build of Android or iOS as those would require a way to spin up an emulator, deploy/run the app, wait for finish, remove the app and shutdown the emulator before returning results.

If there's a way to automate this for iOS/Android, I'd be happy to work with someone to figure out how to integrate things.

In theory the runners have a Writer property that could be used to send data to a listening socket or log file, but there may be a bug with this mechanism as it's not well used (#39).

**Comment by onovotny** [comment]
Closing for now; the bug mentioned was resolved.
