### ISSUE TITLE
Update nuget / when I update Xam Forms and other support libs, this lib causes a downgrade

### ISSUE THREAD

**Issue by robertbaker** [xunit/devices.xunit#43]
When I updated xam forms and the android support libs to the latest versions (23.2), nuget will go through and update, but then the dependency on this package will then initiate a downgrade of devices.xunit and xamarin forms.

If I update devices.xunit back to 2.0, then it will downgrade other libs.

It gets stuck in a weird cycle. Not sure if it's a nuget bug, but one way to fix it would be to release a nuget update bumping the version numbers in the nuspec, which you have done recently.

**Comment by robertbaker** [comment]
Could you do a pre-release version?

**Comment by onovotny** [comment]
I've just pushed out an update to bring Xamarin Forms up to 2.3. Please re-open if still an issue.
