### ISSUE TITLE
System.MissingMethodException: Method 'Forms.Init' not found

### ISSUE THREAD

**Issue by paulanthonymorris** [xunit/devices.xunit#45]
The Android test runner is failing with this exception when I try to upgrade XForms to something greater than 2.1.x. I have scoured everything to make sure I don't have XForms assemblies of another version. Is no one else getting this?

**Comment by Bowman74** [comment]
Same error, clean Android project.

**Comment by tiksn** [comment]
I have the same issue

**Comment by onovotny** [comment]
I've just pushed out an update to bring Xamarin Forms up to 2.3. Please re-open if still an issue.

**Comment by Bowman74** [comment]
That fixed it, thanks!
