### ISSUE TITLE
Cannot reference UWP Application

### ISSUE THREAD

**Issue by matelich** [xunit/devices.xunit#62]
VS2017 v15.4.5
xunit.runner.devices v2.3.2
xunit v2.3.1

Followed https://xunit.github.io/docs/getting-started-devices-uwp.html and works successfully on x86 and ARM.
Upon adding a reference to my UWP application, I get an error:

> 3>error PRI175 : 0x80073b0f - Processing Resources failed with error : Duplicate Entry.
> 3>GENERATEPROJECTPRIFILE : error PRI277: 0xdef00532 - Conflicting values for resource ''

Do I have to move all logic I want tested to a class library?

**Comment by onovotny** [comment]
> Do I have to move all logic I want tested to a class library?

Unfortunately, yes. UWP testing requires an app and it doesn't seem like an app can reference an app.

**Comment by matelich** [comment]
Ok, bummer.  Thanks for getting back to me.
