### ISSUE TITLE
2.3.x fails to perform test discovery on Android

### ISSUE THREAD

**Issue by borrrden** [xunit/devices.xunit#64]
This problem seems specific to Android.  iOS projects are using 2.3.3 without issue for the same set of tests.

Not sure what is going on or how to get more information but using the latest stable version of xunit (2.3.1) and xunit.runner.devices 2.2.0 when the unit test app starts I see an activity indicator and then a list of test assemblies and tests inside.  

I couldn't attempt the xunit 2.3.1 / runner 2.3.0 combination because it seems that they import different versions of xunit.execution.dotnet which multiply defines types.

Changing nothing except upgrading to xunit.runner.devices 2.3.2 or 2.3.3 causes the UI to show no test assemblies.  Are there any changes needed to the way that `AddExecutionAssembly` or `AddTestAssembly` are used?

**Comment by cwrea** [comment]
I am experiencing this issue as well with xunit.runner.devices.2.3.3. Tests are not being discovered in my Android unit test app build.

However, I notice the problem only occurs when my Android project's *Android Options* tab has the option "Use Fast Deployment (debug mode only)" unchecked. If the option is checked (which also requires the "Use Shared Runtime" option to be checked), then tests are discovered.

But I'd like to be able to run tests in a release build and without relying on the shared runtime.

**Comment by cwrea** [comment]
I can confirm that downgrading xunit.runner.devices to v2.2.0 gets test discovery working again, and without requiring "Use Fast Deployment (debug mode only)" nor "Use Shared Runtime". With v2.2.0 I am able to deploy a release build to a device, which has neither of those options checked, and tests are bring discovered.

**Comment by onovotny** [comment]
I'm looking into this, but I think there's something with the Linker.

I was able to repro, but debugging is hard since the debugger won't attach in the scenario. I got it to work by setting the Android Options linker mode to None and turning off "Optimize code" on the Build tab.


In that, it works without the shared runtime. I'll keep digging, but this hopefully can unblock you.

**Comment by pasn** [comment]
It seems that you are right @onovotny . I was playing with [custom linker configuration](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker) and the minimal configuration that I found working was:
  <assembly fullname="xunit.core">
    <type fullname="Xunit.FactAttribute" />
    <type fullname="Xunit.InlineData" />
    <namespace fullname="Xunit.Sdk" />
  </assembly>
  <assembly fullname="xunit.execution.dotnet" />
  <assembly fullname="xunit.runner.devices">
    <type fullname="Xunit.Runners.AutomationTextCellRenderer" />
    <type fullname="Xunit.Runners.TestAssemblyViewModel" />
    <type fullname="Xunit.Runners.TestCaseViewModel" />
    <type fullname="Xunit.Runners.TestResultViewModel" />
    <type fullname="Xunit.Runners.HomeViewModel" />
  </assembly>

Could you add `[Preserve(AllMembers=True)]` attribute to all or at least some of these classes?

**Comment by onovotny** [comment]
I can't add those to the main xUnit libs, but it looks like that config file can be added to the devices with the `LinkDescription` build action:
https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker

**Comment by pasn** [comment]
That's right. If you are doing something like this, I would recommend to include full assemblies without specifying types and namespaces. Linker's configuration that I presented above seems to be fragile for future changes. I would rather recommend something like this:

```
  <assembly fullname="xunit.core" />
  <assembly fullname="xunit.execution.dotnet" />
  <assembly fullname="xunit.runner.devices" />
```
