### ISSUE TITLE
Wrong version of xunit.runner.utility.netstandard installed with the latest package version

### ISSUE THREAD

**Issue by karlingen** [xunit/devices.xunit#78]
I'm not sure if this is a xamarin, mono, nuget or a broken `csproj` file. But I get this error when I update to the latest version of this package (`2.5.18`). 

```
MTOUCH: Error MT2017: Could not process XML description: Failed to resolve assembly: 'xunit.runner.utility.netstandard20, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' (MT2017) (MyApp.Tests.iOS)
```
Browsing through my installed packages I found out that the latest version of this package  includes the following dlls inside `lib/xamarinios10`: 
```
xunit.runner.devices.dll
xunit.runner.devices.xml
xunit.runner.utility.netstandard15.dll
```

Installing version `2.4.48` includes the following files: 
```
xunit.runner.devices.dll
xunit.runner.devices.xml
xunit.runner.utility.netstandard20.dll
```
I was able to build my project if I downgraded `xunit.runner.devices`

Obviously `2.5.18` should include netstandard20 and not netstandard15.

Any ideas why it's behaving like this?

**Comment by onovotny** [comment]
Sorry, that was an oversight. Fixed in 5.2.20.
